#!/bin/bash
# This script updates the server files from GitHub.

if ! [ $(id -u) = 0 ]; then
   echo "Run this script as a root user."
   exit
fi

cd /srv/samba/GitHub
rm -rf /srv/samba/GitHub/repo

mkdir /srv/samba/GitHub/repo
git clone --depth=1 https://github.com/bphett/MediaManagement /srv/samba/GitHub/repo
chmod -R +x /srv/samba/GitHub/repo/

service sickrage stop

if [ -d "/srv/samba/GitHub/repo/etc" ]; then
cp -rf /srv/samba/GitHub/repo/etc/* /etc
fi

if [ -d "/srv/samba/GitHub/repo/home" ]; then
cp -rf /srv/samba/GitHub/repo/home/* /home
fi

if [ -d "/srv/samba/GitHub/repo/opt" ]; then
cp -rf /srv/samba/GitHub/repo/opt/* /opt
fi

if [ -d "/srv/samba/GitHub/repo/srv" ]; then
cp -rf /srv/samba/GitHub/repo/srv/* /srv
fi

service sickrage start
