#!/bin/bash
# This script updates the server files from GitHub.

if ! [ $(id -u) = 0 ]; then
   echo "Run this script as a root user."
   exit
fi

cd /srv/samba/GitHub
#rm -rf /srv/samba/GitHub/*

git reset --hard HEAD
git clean -xffd
git pull --depth=1
#git clone --depth=1 https://github.com/bphett/MediaManagement /srv/samba/GitHub
