#!/bin/bash

#while read line
#do
#   curl "$line"
#done <
if [ -d "/media/MediaServer/Trailers" ]
then
    echo "debug" > /media/MediaServer/Trailers/debug.txt
    find /media/MediaServer/Trailers/* -delete
else
    mkdir "/media/MediaServer/Trailers"
fi
#rm -rf /media/MediaServer/Trailers
#sleep 5
#mkdir -p "/media/MediaServer/Trailers"
if [ ! -d "/media/MediaServer/Trailers" ]; then exit; fi

#for name in $(
#curl -s http://www.imdb.com/chart/boxoffice | sed 's/</\
#/g' | grep '/title/tt' | cut -d\" -f2 | sed 's/^/http:\/\/www.imdb.com/' | sed 's/?.*//' | sed -n 'g;n;p' | sed '6,$d'
#)
#>> /media/MediaServer/MediaServerFiles/Logs/trailerlog.txt
#exit

#do
echo "Getting trailer for test" >> /media/MediaServer/MediaServerFiles/Logs/trailerlog.txt
echo -e "\r"
/home/gettrailer.sh http://www.imdb.com/title/tt3300542 >> /media/MediaServer/MediaServerFiles/Logs/trailerlog.txt
echo -e "\r" >> /media/MediaServer/MediaServerFiles/Logs/trailerlog.txt
#done
# | head -5
now="$(date)"
echo "Trailers pulled at $now" >> /media/MediaServer/MediaServerFiles/Logs/trailerlog.txt
echo -e "\r" >> /media/MediaServer/MediaServerFiles/Logs/trailerlog.txt
