#!/bin/sh
# script to check for complete torrents in transmission folder, then
# stop and move them

# either hard-code the MOVEDIR variable here…
MOVEDIR=/media/MediaServer/MediaServerFiles/CompletedTorrents # the folder to move completed downloads to
# …or set MOVEDIR using the first command-line argument
# MOVEDIR=%1
DELDIR=/media/MediaServer/MediaServerFiles/Delete
PROCDIR=/media/MediaServer/MediaServerFiles/Processing
TEMPDIR=/media/MediaServer/MediaServerFiles/Temporary
LOSTDIR=/media/MediaServer/NewFiles/LostFiles

# logs all output to log file
#LOGFILE=/media/MediaServer/MediaServerFiles/Logs/boot-log.txt # the log file to use
#exec 3>&1 4>&2
#trap 'exec 2>&4 1>&3' 0 1 2 3
#exec >> $LOGFILE 2>&1 # everything below this line will be logged
# echo 'Logging Started ... '

# use transmission-remote to get torrent list from transmission-remote list
# use sed to delete first / last line of output, and remove leading spaces
# use cut to get first field from each line
TORRENTLIST=$(transmission-remote --auth=jaycee5585:jedihunter --list | sed -e '1d;$d;s/^ *//' | cut --only-delimited --delimiter=' ' --fields=1)
echo " ***** TORRENT LIST is "
echo $TORRENTLIST
echo " *****     "'\r'
# for each torrent in the list
for TORRENTID in $TORRENTLIST
do
  TORRENTID=$(echo $TORRENTID | sed 's:*::')
  # removes asterisk * from torrent ID# which had error associated with it
  echo "***** Operations on torrent ID $TORRENTID starting. *****  "'\r'
  LOCATION=$(transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --info | grep "Location:" )
  echo "LOCATION is $LOCATION"'\r'

  # if the torrent is in the Completed Folder…
  case "$LOCATION" in
      *"$MOVEDIR"*)
         echo "Moving files from completed directory. "'\r'
         transmission-remote 9091 --auth=jaycee5585:jedihunter --torrent $TORRENTID --move $TEMPDIR/COMPLETED/$TORRENTID
         wait
         echo ""'\r'
         ;;
      *)
         echo "Torrent not in Completed Directory."'\r'
         ;;
  esac
#  case "$LOCATION" in
#      *"$MOVEDIR"*)
#         echo "Moving files to temporary directory. "'\r'
#         transmission-remote 9091 --auth=jaycee5585:jedihunter --torrent $TORRENTID --move $MOVEDIR/$TORRENTID
#         wait
#         echo ""'\r'
#         ;;
#      *) echo "Torrent not in Completed Directory."'\r'
#         ;;
#  esac
echo "***** Operations on torrent ID $TORRENTID completed. *****     "'\r'

done

#delete folders and excess files
echo " "'\r'
echo "Deleting folders..."'\r'

#rm -rf $PROCDIR/*
rm -rf $MOVEDIR/*
#find $MOVEDIR/* -type d -empty -delete

echo " "'\r'
echo " "'\r'

# move files back to their directories

for TORRENTID in $TORRENTLIST
do
  TORRENTID=$(echo $TORRENTID | sed 's:*::')
  # removes asterisk * from torrent ID# which had error associated with it
  echo "***** Operations on torrent ID $TORRENTID starting. *****  "'\r'
  LOCATION=$(transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --info | grep "Location:" )
  echo "LOCATION is $LOCATION"'\r'

  # if the torrent is in the Temporary Folder…
  case "$LOCATION" in
      *"$TEMPDIR/COMPLETED"*)
         echo "Moving files from temporary directory. "'\r'
         transmission-remote 9091 --auth=jaycee5585:jedihunter --torrent $TORRENTID --move $MOVEDIR/$TORRENTID
         wait
         echo ""'\r'
         ;;
      *)
         echo "Torrent not in temporary Directory."'\r'
         ;;
  esac
done

find $TEMPDIR -type d -empty -delete
#rm -rf $TEMPDIR/*
