#!/bin/sh
# script to check for complete torrents in transmission folder, then
# stop and move them

# either hard-code the MOVEDIR variable here…
MOVEDIR=/media/MediaServer/MediaServerFiles/CompletedTorrents # the folder to move completed downloads to
# …or set MOVEDIR using the first command-line argument
# MOVEDIR=%1
DELDIR=/media/MediaServer/MediaServerFiles/Delete
PROCDIR=/media/MediaServer/MediaServerFiles/Processing

# logs all output to log file
LOGFILE=/media/MediaServer/MediaServerFiles/Logs/transmission-log.txt # the log file to use
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec >> $LOGFILE 2>&1 # everything below this line will be logged
# echo 'Logging Started ... '

# use transmission-remote to get torrent list from transmission-remote list
# use sed to delete first / last line of output, and remove leading spaces
# use cut to get first field from each line
TORRENTLIST=$(transmission-remote --auth=jaycee5585:jedihunter --list | sed -e '1d;$d;s/^ *//' | cut --only-delimited --delimiter=' ' --fields=1)
echo " ***** TORRENT LIST is "
echo $TORRENTLIST
echo " *****     "'\r'
# for each torrent in the list
for TORRENTID in $TORRENTLIST
do
  TORRENTID=$(echo $TORRENTID | sed 's:*::')
  # removes asterisk * from torrent ID# which had error associated with it
  echo "***** Operations on torrent ID $TORRENTID starting. *****  "'\r'
  # check if torrent download is completed
  DL_COMPLETED=$(transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --info | grep "Percent Done: 100%")
  echo "DL_COMPLETED is $DL_COMPLETED"'\r'
  # check torrent’s current state is “Stopped”, “Finished”, or “Idle”
  STATE_STOPPED=$(transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --info | grep "State: Finished")
  echo "STATE_STOPPED is $STATE_STOPPED"'\r'
  # check if state is "Seeding"
  RATIO=$(transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --info | grep "Ratio:" | sed 's/  Ratio: //' | printf "%.0f\n" )
  echo "RATIO is $RATIO"'\r'
  LOCATION=$(transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --info | grep "Location:" )
  echo "LOCATION is $LOCATION"'\r'

  # if the torrent is “Finished” after downloading 100%…
  if [ "$DL_COMPLETED" = "  Percent Done: 100%" ] && [ "$LOCATION" = "  Location: /media/MediaServer/MediaServerFiles/ActiveTorrents" ]; then
    # copy files to post-proc directory if done downloading
    echo "Moving files to processing directory. "'\r'
    transmission-remote 9091 --auth=jaycee5585:jedihunter --torrent $TORRENTID --move $PROCDIR/$TORRENTID
    wait
    Now=$(date)
    echo "AMC finished at: $Now" >> /media/MediaServer/MediaServerFiles/Logs/amc-log.txt
  else
    if [ "$DL_COMPLETED" = "  Percent Done: 100%" ] && [ "$STATE_STOPPED" = "  State: Finished" ] && [ "$LOCATION" = "  Location: $MOVEDIR/$TORRENTID" ]; then
      # move the files and remove the torrent from Transmission
      echo "Torrent #$TORRENTID is completed. "'\r'
      echo "Moving downloaded files to be deleted. "
      # echo " Deldir is #$DELDIR. "
      # echo " Torrent ID is #$TORRENTID"
      transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --move $DELDIR
      wait
      echo " "'\r'
      echo " Removing torrent from list. "
      transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --remove
      wait
      echo " "'\r'
      # delete files
      rm -rf /media/MediaServer/MediaServerFiles/Delete/*
    else
      echo "Torrent #$TORRENTID is not completed. Ignoring. "'\r'
    fi
  fi
  echo "***** Operations on torrent ID $TORRENTID completed. *****     "'\r'

if [ "$LOCATION" = "  Location: $PROCDIR/$TORRENTID" ]; then

#sudo filebot -script /home/jason/scripts/amc.groovy --output "/media/MediaServer/NewFiles" --log-file '/media/MediaServer/MediaServerFiles/Logs/amc-log.txt' --action copy -non-strict "$PROCDIR/$TORRENTID" --def "seriesFormat=/media/MediaServer/NewFiles/{n} ({y})/{'Season '+s}/{n} - {s00e00} - {t} - HDTV {vf} {vc}" >> /media/MediaServer/MediaServerFiles/check$TORRENTID.txt
sudo filebot -script fn:amc --output "/media/MediaServer/NewFiles" --log-file '/media/MediaServer/MediaServerFiles/Logs/amc-log.txt' --action copy -non-strict "$PROCDIR/$TORRENTID" --def "seriesFormat=/media/MediaServer/NewFiles/Shows/{n} ({y})/{'Season '+s}/{n} - {s00e00} - {t} - HDTV {vf} {vc}" >> /media/MediaServer/MediaServerFiles/check$TORRENTID.txt

sleep 60
pattern="Done "
   if grep -q "$pattern" /media/MediaServer/MediaServerFiles/check$TORRENTID.txt; then
#      echo "It worked" >> /media/MediaServer/result.txt
      transmission-remote --auth=jaycee5585:jedihunter --torrent $TORRENTID --move $MOVEDIR/$TORRENTID
   fi
rm -rf /media/MediaServer/MediaServerFiles/check$TORRENTID.txt
fi

done

echo " "'\r'
echo " "'\r'

# check for exceptions and move them
exceptions=$(cat "/media/MediaServer/MediaServerFiles/postexceptions.txt")
IFSOLD=$IFS
IFS=$'\n::'
for exclude in $exceptions; do
   exclude=$(echo "$exclude" | sed "s/\r//")
   IFS=$IFSOLD
   if [ -d "/media/MediaServer/NewFiles/Shows/$exclude" ]; then
       mv -f /media/MediaServer/NewFiles/Shows/$exclude /media/MediaServer/NewFiles
   fi
   IFS=$'\n::'
done
IFS=$IFSOLD
